<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFrameworks>net10.0</TargetFrameworks>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<None Remove="template\blogs.html.tpl" />
		<None Remove="template\docs.html.tpl" />
		<None Remove="template\docsSearch.html.tpl" />
		<None Remove="template\index.html.tpl" />
		<None Remove="template\product.html.tpl" />
		<None Remove="template\productSearch.html.tpl" />
		<None Remove="template\web.zip" />
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Include="template\docs.html.tpl" />
		<EmbeddedResource Include="template\docsSearch.html.tpl" />
		<EmbeddedResource Include="template\blogContent.html.tpl" />
		<EmbeddedResource Include="template\blogs.html.tpl" />
		<EmbeddedResource Include="template\index.html.tpl" />
		<EmbeddedResource Include="template\product.html.tpl" />
		<EmbeddedResource Include="template\productSearch.html.tpl" />
		<EmbeddedResource Include="template\web.zip" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Markdig" Version="0.44.0" />
		<PackageReference Include="Spectre.Console" Version="0.55.0" />
		<PackageReference Include="Microsoft.Extensions.Localization" Version="10.0.3" />
	</ItemGroup>

	<PropertyGroup>
		<SatelliteResourceLanguages>zh-CN;en-US</SatelliteResourceLanguages>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\ColorCode.HTML\ColorCode.HTML.csproj" />
		<ProjectReference Include="..\Models\Models.csproj" />
	</ItemGroup>

</Project>
