<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFrameworks>net8.0;net10.0</TargetFrameworks>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<PackAsTool>true</PackAsTool>
		<ToolCommandName>ezdoc</ToolCommandName>
		<PackageOutputPath>./nupkg</PackageOutputPath>
		<PackageId>Ater.EasyDocs</PackageId>
		<Version>2.1.0</Version>
		<Description>Fast and lightweight static website generation tool!</Description>
		<Authors>NilTor</Authors>
		<Company>Atersoft</Company>
		<Copyright>Atersoft</Copyright>
		<SatelliteResourceLanguages>en</SatelliteResourceLanguages>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<PackageProjectUrl>https://github.com/AterDev/easyblog</PackageProjectUrl>
		<RepositoryType>git</RepositoryType>
		<RepositoryUrl>https://github.com/AterDev/easyblog.git</RepositoryUrl>
		<PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>
		<PackageReleaseNotes>add net10 support</PackageReleaseNotes>
		<ImplicitUsings>enable</ImplicitUsings>
		<AssemblyName>$(MSBuildProjectName)</AssemblyName>
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
		<PackageTags>ater;cli;code generate;angular;webapi;asp.net core</PackageTags>
		<Nullable>enable</Nullable>
		<Title>EasyDocs</Title>
		<SatelliteResourceLanguages>None</SatelliteResourceLanguages>
		<PackageIcon>logo.jpg</PackageIcon>
		<PackageReadmeFile>README.md</PackageReadmeFile>
	</PropertyGroup>
	<ItemGroup>
		<ProjectReference Include="..\Share\Share.csproj" />
	</ItemGroup>
	<ItemGroup>
	  <None Include="logo.jpg">
	    <Pack>True</Pack>
	    <PackagePath>\</PackagePath>
	  </None>
	  <None Include="README.md">
	    <Pack>True</Pack>
	    <PackagePath>\</PackagePath>
	  </None>
	</ItemGroup>


</Project>
