<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <OutDir>bin</OutDir>
        <NodeApiAssemblyJSModuleType>esm</NodeApiAssemblyJSModuleType>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.JavaScript.NodeApi.Generator" Version="0.9.18" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Share\Share.csproj" />
    </ItemGroup>
</Project>
